### ISSUE TITLE
Error loading chart datasources. Filters may not work correctly.

### ISSUE THREAD

**Issue by mchamyan** [timescale/nft-starter-kit#1]
Hi.

I'm new and starting to set up the nft-starter-kit. 
After following all steps of the tutorial im heading towards the dashboard and my data isn't loading.
Im having the following error "Error loading chart datasources. Filters may not work correctly." I haven't set any filters so I think thats not the problem.

Thanks,

mmm

<img width="852" alt="Captura de Pantalla 2021-11-21 a la(s) 11 39 19" src="https://user-images.githubusercontent.com/94792953/142766370-f27922d6-befd-49dc-8c9c-dcc6255352c2.png">

**Comment by zseta** [comment]
Hi @mchamyan !
Have you got any error messages while running `docker-compose up` ?
Also have you waited until docker-compose finished setting up the database? (see this message in the terminal: `timescaledb_1      | PostgreSQL init process complete; ready for start up.`)

**Comment by mchamyan** [comment]
Hi zseta, thanks for your answer.

Got this error messages:

```
timescaledb_1      |2021-11-22 18:40:59.005 UTC [88] ERROR:  invalid input syntax for type bigint: "oid sha256:03976df62abaae9fc8aa4e521a7a5a6dab682ef0bbc3f1c0799f57dd24507e74"
timescaledb_1      | 2021-11-22 18:40:59.005 UTC [88] CONTEXT:  COPY assets, line 2, column id: "oid sha256:03976df62abaae9fc8aa4e521a7a5a6dab682ef0bbc3f1c0799f57dd24507e74"
timescaledb_1      | 2021-11-22 18:40:59.005 UTC [88] STATEMENT:  COPY  assets FROM STDIN CSV HEADER;
timescaledb_1      | ERROR:  invalid input syntax for type bigint: "oid sha256:03976df62abaae9fc8aa4e521a7a5a6dab682ef0bbc3f1c0799f57dd24507e74"
timescaledb_1      | CONTEXT:  COPY assets, line 2, column id: "oid sha256:03976df62abaae9fc8aa4e521a7a5a6dab682ef0bbc3f1c0799f57dd24507e74"
```
```
timescaledb_1      | 2021-11-22 18:41:07.184 UTC [88] ERROR:  insert or update on table "_hyper_1_1_chunk" violates foreign key constraint "1_2_nft_sales_asset_id_fkey"
timescaledb_1      | 2021-11-22 18:41:07.184 UTC [88] DETAIL:  Key (asset_id)=(37266827) is not present in table "assets".
timescaledb_1      | 2021-11-22 18:41:07.184 UTC [88] CONTEXT:  COPY nft_sales, line 589756: ""
timescaledb_1      | 2021-11-22 18:41:07.184 UTC [88] STATEMENT:  COPY  nft_sales FROM STDIN CSV HEADER;
timescaledb_1      | ERROR:  insert or update on table "_hyper_1_1_chunk" violates foreign key constraint "1_2_nft_sales_asset_id_fkey"
timescaledb_1      | DETAIL:  Key (asset_id)=(37266827) is not present in table "assets".
timescaledb_1      | CONTEXT:  COPY nft_sales, line 589756: ""
```
I can see the `timescaledb_1 | PostgreSQL init process complete; ready for start up.` message. 

Thanks again.

Martin

**Comment by zseta** [comment]
Hi @mchamyan !
Could you have a look at the `asset.csv` file in the `pre-built-dashboards/database/data/` folder?
Based on this error message you have:
```bash
ERROR:  invalid input syntax for type bigint: "oid sha256:03976df62abaae9fc8aa4e521a7a5a6dab682ef0bbc3f1c0799f57dd24507e74"
```
My guess is that when you cloned the repo this file didn't download properly for some reason. Maybe try cloning the repo again?

**Comment by waqasakramef** [comment]
I'm facing this issue while I have imported dashboards from Apache Superset 1.4.2 to 2.0.

**Comment by YashatXYZCo** [comment]
> I'm facing this issue while I have imported dashboards from Apache Superset 1.4.2 to 2.0.

Hi @waqasakramef, I'm having the same issue, any update?

**Comment by zseta** [comment]
Hi @waqasakramef and @YashatXYZCo ,
I just ran a quick test, and while I also see this error message (`Error loading chart datasources. Filters may not work correctly. `) the charts and the filter panel does seem to work just fine. I guess the problem is that this dashboard was created with the old Filter panel that Superset had and now they have a "filter sidebar" instead. But using the Filter panel the dashboard should work fine.

**Comment by YashatXYZCo** [comment]
Hi @zseta 
Thanks, it's working for me as well, miraculously.

**Comment by zseta** [comment]
Great! feel free to reopen if issues arise in the future.

**Comment by yanickrochon** [comment]
@zseta  why haven't old filters been upgraded then? The breaking change p***es a lot of people over here.

**Comment by zseta** [comment]
Hi @yanickrochon 
I agree the new filters would be better but AFAIK it is not a breaking change. Anyways, I'm happy to review PRs that improve this project - unfortunately, I haven't had the chance to work on this repo in a while.

**Comment by LeoDiep** [comment]
> Hi @waqasakramef and @YashatXYZCo , I just ran a quick test, and while I also see this error message (`Error loading chart datasources. Filters may not work correctly. `) the charts and the filter panel does seem to work just fine. I guess the problem is that this dashboard was created with the old Filter panel that Superset had and now they have a "filter sidebar" instead. But using the Filter panel the dashboard should work fine.

Hi @zseta  
I was importing dashboards from Superset v1.5.0 to new Superset v2.1.0 and this error notice appear everytime I access or reload the dasboard. On the old superset, these dashboards only use filter sidebar on the left, and when they are imported to new superset, I have to edit the scope manually again but they work just fine, the charts running the same as the old superset.

However the error notice is confusing other users and it's annoying them. Please help me fix this.
Thank you

**Comment by lowlandsheperd** [comment]
> > Hi @waqasakramef and @YashatXYZCo , I just ran a quick test, and while I also see this error message (`Error loading chart datasources. Filters may not work correctly. `) the charts and the filter panel does seem to work just fine. I guess the problem is that this dashboard was created with the old Filter panel that Superset had and now they have a "filter sidebar" instead. But using the Filter panel the dashboard should work fine.
> 
> Hi @zseta I was importing dashboards from Superset v1.5.0 to new Superset v2.1.0 and this error notice appear everytime I access or reload the dasboard. On the old superset, these dashboards only use filter sidebar on the left, and when they are imported to new superset, I have to edit the scope manually again but they work just fine, the charts running the same as the old superset.
> 
> However the error notice is confusing other users and it's annoying them. Please help me fix this. Thank you

try this:
https://github.com/apache/superset/issues/25269

**Comment by LeoDiep** [comment]
> try this: [apache/superset#25269](https://github.com/apache/superset/issues/25269)

Thank you for your suggestions, I will use it next time when I upgrade to another version (I did manually click into every datasets and save to overwrite them and the error notification dissapeared)
