### ISSUE TITLE
Data ingestion script gives KeyError

### ISSUE THREAD

**Issue by hwixley** [timescale/nft-starter-kit#15]
Hi there!

I have done all the setup for this project (installed postgreSQL & timescaleDB, connected to timescaleDB cloud instance, and set up `config.py`). However, upon execution I got a KeyError:

![nft-scraper-issue](https://user-images.githubusercontent.com/57837950/155733962-55b19427-e2fb-455c-9804-4bef04245332.png)

Do you know what went wrong and how I could fix this?

Thanks!

**Comment by zseta** [comment]
Hi @hwixley !
When did you clone the repo? I've very recently pushed [a fix](https://github.com/timescale/nft-starter-kit/pull/12) for this problem. I suggest doing a pull and reinstall requirements:
```
git pull
source env/bin/activate
pip install -r requirements.txtx
```

**Comment by hwixley** [comment]
Yes this worked!! Thanks so much @zseta :rocket:
