### ISSUE TITLE
Request blocked

### ISSUE THREAD

**Issue by alimcharaniya** [timescale/nft-starter-kit#3]
Followed the instructions, got the db connected. When running opensea_ingest.py i'm seeing

```
Fetching transactions from OpenSea...
None
Request blocked... retrying...

```

outputted in console... I realized now I dont have an OpenSea API key. Is this why?

**Comment by zseta** [comment]
Hi @alimcharaniya 
Yes, you can request an API key here: https://docs.opensea.io/reference/request-an-api-key
