### ISSUE TITLE
NFT-Starter Kit "No such file or directory

### ISSUE THREAD

**Issue by andrew0306** [timescale/nft-starter-kit#8]
I am cloning and facing this issue after building the containers. Any help or ideas would be greatly appreciated.
![Issue](https://user-images.githubusercontent.com/99380234/153335789-941629e1-c343-4a0a-bf5c-9bf8187fba88.PNG)

**Comment by andrew0306** [comment]
![Docker issue](https://user-images.githubusercontent.com/99380234/153336144-ced821d1-1667-4ce8-9666-c6118c9a6f4b.PNG)
Here is some additional output

**Comment by andrew0306** [comment]
Hi @zseta , im not sure if you saw my last message but I am using Docker-Compose v 2.2.3

**Comment by pulsarforge** [comment]
Hi @zseta  I found the same issues, I solved by running the docker compose from wsl ubuntu command line inside visual studio code from windows. It works properly.
